name: Deploy to Existing Compute Engine VM

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Compute Engine
        run: |
          gcloud compute ssh instance-20250227-065113 --zone=asia-northeast3-c --command="
            cd AI-Server || git clone https://github.com/WriteAgain/AI-Server.git && cd AI-Server
            git pull origin main
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            pip3 install -r requirements.txt
            export BACKEND_SERVER=\"34.64.248.152\"
            export OPENAI_API_KEY=\"\$(gcloud secrets versions access latest --secret=openai-api-key)\"
            nohup python main.py > app.log 2>&1 &
          "